services:
  # Django services
  web:
    build: 
      context: .
      target: runtime
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # DATABASE postgressSQL services
  db:
    image: postgres:16
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mediadb
    ports:
      - "5433:5432"

# Volumes for persistence
volumes:
  postgres_dev_data:
