version: '3.8'

services:
  # Django services
  web:
    build: 
    contecxt: .
    target: runtime
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=local_development_fallback_key_8976
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mediadb
    depends_on:
      - db
# DATABASE postgressSQL services

db:
  image: postgres:16-alpine
  volumes:
    - postgres_dev_data:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=mediadb
  ports:
    - "5433:5432"

# Volumes for persistence
volumes:
  postgres_dev_data:
  