# Generated by Django 6.0.5 on 2026-05-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tmdb_id",
                    models.IntegerField(
                        blank=True,
                        help_text="TMDB ID for external references",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "imdb_id",
                    models.CharField(
                        blank=True,
                        help_text="IMDb ID for external links",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "contnt_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv", "TV Show")],
                        default="movie",
                        max_length=10,
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("overview", models.TextField(blank=True)),
                (
                    "poster_path",
                    models.CharField(
                        blank=True,
                        help_text="CDN path for TMDB poster or custom path",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "custom_poster",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded custom poster if not using TMDB",
                        null=True,
                        upload_to="custom_posters/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
