# Generated by Django 6.0.5 on 2026-05-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
